services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3001/api
        VITE_CLOUDINARY_CLOUD_NAME: your_cloud_name
        VITE_CLOUDINARY_UPLOAD_PRESET: upload_preset
        VITE_CLOUDINARY_UPLOAD_FOLDER: uploads
    depends_on:
      - server
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      JWT_SECRET: your_jwt_secret
      ADMIN_DEFAULT_EMAIL: admin@hublab.com
      ADMIN_DEFAULT_PASSWORD: test1234
      SUPABASE_URL: https://your_project.supabase.co
      SUPABASE_SERVICE_ROLE_KEY: your_supabase_secret
      CLOUDINARY_CLOUD_NAME:
      CLOUDINARY_API_KEY:
      CLOUDINARY_API_SECRET:
