-- =====================================================
-- Schema de la base de datos Route 66 (Supabase / PostgreSQL)
-- =====================================================
-- Ejecutar este script en el SQL Editor de Supabase para crear las tablas
-- en una base nueva. Las relaciones entre tablas se manejan con FKs:
--
--   categorias  <--FK-- platos --FK--> imagenes
--                          |
--                          +--FK--> modelos
--
-- Cada plato pertenece a una categoria y opcionalmente tiene una imagen y
-- un modelo 3D. Imagen y modelo son opcionales (pueden ser null).
--
-- IMPORTANTE: los IDs son integers autoincrement. El backend se encarga de
-- traducir entre estos ids y los strings que usa el frontend ("item-12",
-- "cat-bebidas", etc). Ver server/supabaseStore.js.

-- =====================================================
-- TABLAS PRINCIPALES
-- =====================================================


alter table public.platos
  add column descuento int4 not null default 0
  check (descuento >= 0 and descuento <= 100),
  add column descuento_inicio timestamptz,
  add column descuento_fin timestamptz;

-- index para que las queries con filtros de vigencia sean rapidas
create index if not exists idx_platos_descuento_fin on public.platos (descuento_fin);

-- Tabla de categorias del menu (Bebidas, Hamburguesas, etc).
-- Es la mas simple: solo id y nombre.
create table if not exists public.categorias (
    id_categ int4 generated by default as identity primary key,
    nombre_categ varchar(120) not null
);

-- Catalogo de imagenes subidas (URL de Cloudinary o path local).
-- El UNIQUE en url_image evita que se registre la misma imagen dos veces.
-- El backend lo aprovecha para hacer lookup por URL al guardar un plato.
create table if not exists public.imagenes (
    id_image int4 generated by default as identity primary key,
    nombre_image varchar(180) not null,
    url_image varchar(500) not null unique
);

-- Catalogo de modelos 3D (.glb en Cloudinary). Misma estructura que imagenes.
create table if not exists public.modelos (
    id_model int4 generated by default as identity primary key,
    nombre_model varchar(180) not null,
    url_model varchar(500) not null unique
);

-- =====================================================
-- TABLA PRINCIPAL (DEPENDIENTE)
-- =====================================================

-- Tabla principal: los platos del menu.
-- Tiene FKs a las tres tablas anteriores. Las reglas de cascade son
-- importantes:
--   - categoria: ON DELETE CASCADE -> si borras una categoria, se borran
--     todos sus platos (logico, no tiene sentido un plato sin categoria)
--   - imagen / modelo: ON DELETE SET NULL -> si borras una imagen o modelo,
--     los platos que la usaban quedan con ese campo en null (sin imagen
--     pero sin perder el plato).
create table if not exists public.platos (
    id int4 generated by default as identity primary key,
    nombre varchar(180) not null,
    descripcion varchar(500) not null default '',
    -- precio se guarda como int (centavos NO, pesos enteros).
    -- El frontend manda "$12.990" y el backend hace parseInt limpiando.
    precio int4 not null,
    categoria int4 not null,
    imagen int4,  -- nullable: hay platos sin foto
    modelo int4,  -- nullable: solo algunos platos tienen 3D/AR
    -- Array nativo de Postgres. Mucho mas comodo que una tabla aparte
    -- de "ingredientes_plato". Es texto libre, no normalizado.
    ingredientes text[] not null default '{}',
    -- Color custom para la card del plato. Default = azul oscuro del tema.
    -- Comillas dobles porque cardColor tiene mayuscula y Postgres por
    -- default lowercase a todo. Mismo motivo en cardMessage.
    "cardColor" varchar(7) default '#152238',
    -- Badge tipo "Nuevo!", "Recomendado", etc. Maximo 40 chars (tambien
    -- validado en el backend y en el form del admin).
    "cardMessage" varchar(40),
    constraint fk_platos_categoria
        foreign key (categoria)
        references public.categorias (id_categ)
        on delete cascade,
    constraint fk_platos_imagen
        foreign key (imagen)
        references public.imagenes (id_image)
        on delete set null,
    constraint fk_platos_modelo
        foreign key (modelo)
        references public.modelos (id_model)
        on delete set null,
    -- Valida que cardColor sea hexadecimal valido en formato #RRGGBB.
    -- Doble validacion: front, back y BD. Mejor paranoico que tener data sucia.
    constraint card_color_hex check ("cardColor" ~ '^#[0-9A-Fa-f]{6}$')
);

-- =====================================================
-- TABLAS AUXILIARES
-- =====================================================

-- tabla nueva: historial de colores usados en cardColor de platos
-- guarda los ultimos colores que el admin eligio para reusarlos rapido
create table if not exists public.historial_colores (
    color varchar(7) primary key,
    used_at timestamptz not null default now(),
    constraint historial_color_hex check (color ~ '^#[0-9A-Fa-f]{6}$')
);

-- tabla de usuarios secundarios. el super_admin sigue viviendo en admin.json
-- y bypasea estos permisos. aca van los usuarios con permisos limitados.
create table if not exists public.usuarios (
    id_usuario int4 generated by default as identity primary key,
    email varchar(180) not null unique,
    password_hash varchar(255) not null,
    -- permisos granulares. cada uno controla un area del admin
    puede_crear_platos boolean not null default false,
    puede_editar_platos boolean not null default false,
    puede_eliminar_platos boolean not null default false,
    puede_gestionar_categorias boolean not null default false,
    puede_subir_archivos boolean not null default false,
    puede_eliminar_archivos boolean not null default false,
    puede_gestionar_usuarios boolean not null default false,
    creado_en timestamptz not null default now()
);

-- =====================================================
-- INDICES
-- =====================================================

-- Indices para acelerar las consultas mas frecuentes:
-- - filtrar platos por categoria (seguro que se hace mucho al cargar el menu)
-- - hacer JOINs por imagen o modelo
create index if not exists idx_platos_categoria on public.platos (categoria);
create index if not exists idx_platos_imagen on public.platos (imagen);
create index if not exists idx_platos_modelo on public.platos (modelo);

-- index para ordenar por mas reciente sin escanear toda la tabla
create index if not exists idx_historial_colores_used_at
    on public.historial_colores (used_at desc);

-- index para busqueda rapida por email (login)
create unique index if not exists idx_usuarios_email
    on public.usuarios (lower(email));

-- =====================================================
-- TROUBLESHOOTING
-- =====================================================
-- Si al crear un plato/categoria desde el admin tira error de duplicate key
-- en la PK, es porque la secuencia del autoincrement quedo desfasada
-- (suele pasar despues de inserts manuales o restores). Ejecutar:

-- Para fixear agregar plato:
-- SELECT setval(
--   pg_get_serial_sequence('platos', 'id'),
--   COALESCE((SELECT MAX(id) FROM platos), 0) + 1,
--   false
-- );

-- Para fixear agregar categoría:
-- SELECT setval(
--   pg_get_serial_sequence('categorias', 'id_categ'),
--   COALESCE((SELECT MAX(id_categ) FROM categorias), 0) + 1,
--   false
-- );