-- Ejecutar este script en el SQL Editor de Supabase para una base nueva.

create table if not exists public.categorias (
    id_categ int4 generated by default as identity primary key,
    nombre_categ varchar(120) not null
);

create table if not exists public.imagenes (
    id_image int4 generated by default as identity primary key,
    nombre_image varchar(180) not null,
    url_image varchar(500) not null unique
);

create table if not exists public.modelos (
    id_model int4 generated by default as identity primary key,
    nombre_model varchar(180) not null,
    url_model varchar(500) not null unique
);

create table if not exists public.platos (
    id int4 generated by default as identity primary key,
    nombre varchar(180) not null,
    descripcion varchar(500) not null default '',
    precio int4 not null,
    categoria int4 not null,
    imagen int4,
    modelo int4,
    ingredientes text[] not null default '{}',
    constraint fk_platos_categoria
        foreign key (categoria)
        references public.categorias (id_categ)
        on delete cascade,
    constraint fk_platos_imagen
        foreign key (imagen)
        references public.imagenes (id_image)
        on delete set null,
    constraint fk_platos_modelo
        foreign key (modelo)
        references public.modelos (id_model)
        on delete set null
);

create index if not exists idx_platos_categoria on public.platos (categoria);
create index if not exists idx_platos_imagen on public.platos (imagen);
create index if not exists idx_platos_modelo on public.platos (modelo);
